listen_port: 9220
timeout: 10
job: 'redfish-myjob'
targets:
  server1-example-com:
    host: server1.example.com
    username: admin
    password: changeme
    port: 8868
  server2-example-com:
    host: server2.example.com
    username: admin
    password: changeme
    port: 8874
